"""
utils/aero_table_parser.py — aero_table.h / SimSweep CSV Parser
Trinity 6-DOF Simulator | Orbital Dynamics

Two parsers:

1. AeroTableParser    — reads the C header `aero_table.h` generated by
                        AeroSim Analyzer (Caronte V1 firmware format).
                        Extracts the CL(α) lookup table for FIN aerodynamics.

2. SimSweepAeroParser — reads the CSV exported by SimScale Parametric Sweep
                        (aero_analysis_gui.py → "Export CSV").
                        Extracts Cd(Mach, AoA) and Cn(Mach, AoA) for the
                        rocket body (drag and normal force coefficients).
"""

from __future__ import annotations
import re
from pathlib import Path
from dataclasses import dataclass
import numpy as np
import pandas as pd
from scipy.interpolate import RegularGridInterpolator, LinearNDInterpolator

from core.atmosphere import isa, speed_of_sound, density_to_altitude


# ══════════════════════════════════════════════════════════════════════════════
#  1.  aero_table.h  (CL(α) for individual fins)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class AeroTableFin:
    """
    CL(α) look-up table for a single aerodynamic control fin,
    parsed from the `aero_table.h` file generated by AeroSim Analyzer.

    The table maps commanded lift coefficient CL → required AoA [°].
    The physics engine needs the FORWARD map  AoA → CL, which is the inverse.
    We provide both.
    """
    sref_m2: float                # Reference fin area [m²]
    cl_min: float                 # Minimum CL in the LUT
    cl_max: float                 # Maximum CL in the LUT
    aoa_table_deg: np.ndarray     # AOA values [°] for N points, indexed by CL
    n_points: int

    # Derived: forward table  AoA [°] → CL  (built in __post_init__)
    _aoa_sorted: np.ndarray = None
    _cl_sorted:  np.ndarray = None

    def __post_init__(self):
        # Build the CL values that correspond to each AOA entry
        cl_vals = np.linspace(self.cl_min, self.cl_max, self.n_points)
        # Sort by AOA for forward interpolation
        idx = np.argsort(self.aoa_table_deg)
        self._aoa_sorted = self.aoa_table_deg[idx]
        self._cl_sorted  = cl_vals[idx]

    def cl_from_aoa(self, aoa_deg: float) -> float:
        """Forward map: AoA [°] → CL (unsigned, ≥ 0)."""
        aoa_deg = float(np.clip(abs(aoa_deg), 0.0, self._aoa_sorted[-1]))
        return float(np.interp(aoa_deg, self._aoa_sorted, self._cl_sorted))

    def aoa_from_cl(self, cl: float) -> float:
        """Inverse map: CL → AoA [°] (unsigned)."""
        cl = float(np.clip(abs(cl), self.cl_min, self.cl_max))
        cl_vals = np.linspace(self.cl_min, self.cl_max, self.n_points)
        return float(np.interp(cl, cl_vals, self.aoa_table_deg))

    def fin_force(self, delta_rad: float, q_dyn: float) -> float:
        """
        Compute aerodynamic force [N] for a fin deflected by delta_rad [rad].

        F = CL(|δ|) · q · Sref · sign(δ)
        """
        aoa_deg = abs(np.degrees(delta_rad))
        cl      = self.cl_from_aoa(aoa_deg)
        return float(cl * q_dyn * self.sref_m2 * np.sign(delta_rad))

    def aoa_for_force(self, force_n: float, q_dyn: float) -> float:
        """
        Inverse of fin_force: returns required AoA [°] to produce force_n [N].
        """
        if q_dyn * self.sref_m2 < 1e-6:
            return 0.0
        cl_cmd = abs(force_n) / (q_dyn * self.sref_m2)
        return self.aoa_from_cl(cl_cmd)


def parse_aero_table_h(source: str | Path) -> AeroTableFin:
    """
    Parse a `aero_table.h` file generated by AeroSim Analyzer.

    Reads:
      - AERO_SREF     → fin reference area [m²]
      - AERO_TABLE_N  → number of LUT points
      - AERO_CL_MIN   → min CL
      - AERO_CL_MAX   → max CL
      - AERO_AOA_TABLE → float array of AOA values [°]
    """
    if isinstance(source, (str, Path)) and Path(str(source)).exists():
        text = Path(source).read_text(encoding='utf-8', errors='replace')
    else:
        text = str(source)

    def _find_define_float(name: str) -> float:
        m = re.search(rf'#define\s+{name}\s+([\d.eE+\-]+)f?', text)
        if not m:
            raise ValueError(f"Could not find #define {name} in aero_table.h")
        return float(m.group(1))

    def _find_define_int(name: str) -> int:
        m = re.search(rf'#define\s+{name}\s+(\d+)', text)
        if not m:
            raise ValueError(f"Could not find #define {name} in aero_table.h")
        return int(m.group(1))

    sref  = _find_define_float('AERO_SREF')
    n     = _find_define_int('AERO_TABLE_N')
    cl_min= _find_define_float('AERO_CL_MIN')
    cl_max= _find_define_float('AERO_CL_MAX')

    # Extract the float array between the braces of AERO_AOA_TABLE
    m = re.search(r'AERO_AOA_TABLE\s*\[.*?\]\s*=\s*\{([^}]+)\}', text, re.DOTALL)
    if not m:
        raise ValueError("Could not find AERO_AOA_TABLE array in aero_table.h")

    raw_floats = re.findall(r'[\d.eE+\-]+', m.group(1))
    aoa_table  = np.array([float(x) for x in raw_floats], dtype=float)

    if len(aoa_table) != n:
        raise ValueError(
            f"AERO_TABLE_N={n} but found {len(aoa_table)} values in AERO_AOA_TABLE"
        )

    return AeroTableFin(
        sref_m2     = sref,
        cl_min      = cl_min,
        cl_max      = cl_max,
        aoa_table_deg = aoa_table,
        n_points    = n,
    )


# ══════════════════════════════════════════════════════════════════════════════
#  2.  SimSweep CSV  (Cd / Cn vs Mach and AoA for the rocket body)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class BodyAeroModel:
    """
    2-D aerodynamic coefficient model for the rocket body,
    built from SimScale parametric sweep results.

    Provides:
      Cd(Mach, AoA_deg) — drag coefficient
      Cn(Mach, AoA_deg) — normal force coefficient (lift in wind frame)
    """
    aref_m2: float                # Body reference area [m²] (= π r²)
    mach_range: tuple[float, float]
    aoa_range:  tuple[float, float]
    _cd_interp: object = None     # 2D interpolator
    _cn_interp: object = None

    def Cd(self, mach: float, aoa_deg: float) -> float:
        """Drag coefficient at (Mach, AoA). AoA may be negative (mirror)."""
        aoa_abs = abs(aoa_deg)
        if self._cd_interp is None:
            return 0.45  # fallback
        try:
            return max(0.0, float(self._cd_interp([[mach, aoa_abs]])))
        except Exception:
            return 0.45

    def Cn(self, mach: float, aoa_deg: float) -> float:
        """Normal-force coefficient at (Mach, AoA)."""
        aoa_abs = abs(aoa_deg)
        if self._cn_interp is None:
            return 0.0
        try:
            return float(self._cn_interp([[mach, aoa_abs]]))
        except Exception:
            return 0.0

    def drag_force(self, mach: float, aoa_deg: float,
                   q_dyn: float) -> float:
        """Drag magnitude [N]."""
        return self.Cd(mach, aoa_deg) * q_dyn * self.aref_m2

    def normal_force(self, mach: float, aoa_deg: float,
                     q_dyn: float) -> float:
        """Normal (lift) force magnitude [N]."""
        return self.Cn(mach, aoa_deg) * q_dyn * self.aref_m2


def parse_simsweep_csv(
        path: str | Path,
        diameter_m: float,
        aref_m2: float | None = None,
) -> BodyAeroModel:
    """
    Build a BodyAeroModel from a SimScale Parametric Sweep CSV file
    (as exported by `aero_analysis_gui.py`).

    Expected CSV columns (minimum):
        speed_ms, aoa_deg, density_kgm3, drag_N, lift_N

    Optional (also accepted):
        status  — only rows where status == 'FINISHED' are used
        Mach    — if present, used directly; otherwise computed from ISA

    Parameters
    ----------
    path : str or Path
        Path to the CSV file.
    diameter_m : float
        Rocket body diameter [m], used to compute Aref = π(d/2)².
    aref_m2 : float, optional
        Override reference area. Defaults to circle from diameter_m.
    """
    df = pd.read_csv(path)

    # Filter to finished simulations only
    if 'status' in df.columns:
        df = df[df['status'].str.upper() == 'FINISHED'].copy()

    if df.empty:
        raise ValueError(f"No FINISHED simulation rows found in {path}")

    required = {'speed_ms', 'aoa_deg', 'density_kgm3'}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(f"SimSweep CSV is missing columns: {missing}")

    # Determine force columns
    if 'drag_N' in df.columns and 'lift_N' in df.columns:
        drag_col, lift_col = 'drag_N', 'lift_N'
    elif 'fx' in df.columns and 'fy' in df.columns:
        drag_col, lift_col = 'fx', 'fy'
        df['drag_N'] = -df['fx']   # fx typically along rocket axis (negative = drag)
        df['lift_N'] = df['fy']
        drag_col, lift_col = 'drag_N', 'lift_N'
    else:
        raise ValueError("SimSweep CSV must contain drag_N/lift_N or fx/fy columns")

    # Compute Mach number from speed and density via ISA
    def _row_mach(row):
        alt_approx = density_to_altitude(row['density_kgm3'])
        _, _, T = isa(alt_approx)
        a = speed_of_sound(T)
        return row['speed_ms'] / a if a > 1 else 0.0

    if 'Mach' not in df.columns:
        df['Mach'] = df.apply(_row_mach, axis=1)

    # Reference area
    Aref = aref_m2 if aref_m2 is not None else np.pi * (diameter_m / 2) ** 2

    # Compute non-dimensional coefficients
    q_dyn_arr = 0.5 * df['density_kgm3'].values * df['speed_ms'].values ** 2
    q_dyn_arr = np.maximum(q_dyn_arr, 1e-6)   # avoid division by zero

    df['Cd'] = df[drag_col].abs().values / (q_dyn_arr * Aref)
    df['Cn'] = df[lift_col].abs().values / (q_dyn_arr * Aref)
    df['aoa_abs'] = df['aoa_deg'].abs()

    # Build 2D interpolator over (Mach, |AoA|)
    pts    = df[['Mach', 'aoa_abs']].values
    cd_vals = df['Cd'].values
    cn_vals = df['Cn'].values

    # Try scattered interpolation (tolerates non-regular grids)
    try:
        cd_interp = LinearNDInterpolator(pts, cd_vals, fill_value=float(cd_vals.mean()))
        cn_interp = LinearNDInterpolator(pts, cn_vals, fill_value=0.0)
    except Exception as exc:
        print(f"[AeroParser] Warning: could not build interpolator ({exc}). "
              "Using mean values.")
        cd_interp = None
        cn_interp = None

    mach_range = (float(df['Mach'].min()), float(df['Mach'].max()))
    aoa_range  = (float(df['aoa_abs'].min()), float(df['aoa_abs'].max()))

    model = BodyAeroModel(
        aref_m2    = Aref,
        mach_range = mach_range,
        aoa_range  = aoa_range,
        _cd_interp = cd_interp,
        _cn_interp = cn_interp,
    )
    return model
